# Generated by Django 2.2 on 2019-11-02 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_department_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignemnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('indoor_directions', models.CharField(max_length=128)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(choices=[('MANDATORY', 'MANDATORY'), ('OPTIONAL', 'OPTIONAL')], default='OPTIONAL', max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('credits_number', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_week', models.SmallIntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('frequency', models.SmallIntegerField()),
                ('type', models.CharField(choices=[('COURSE', 'COURSE'), ('SEMINARY', 'SEMINARY'), ('LABORATORY', 'LABORATORY')], default='COURSE', max_length=15)),
                ('formation', models.CharField(max_length=8)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.Room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignemnt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.Assignemnt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.Student')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.Attendance')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.SubjectActivity'),
        ),
        migrations.AddField(
            model_name='assignemnt',
            name='subject_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.SubjectActivity'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.Subject')),
            ],
            options={
                'unique_together': {('subject', 'student')},
            },
        ),
    ]
